<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Facades\Storage;
use JeroenG\Explorer\Application\Explored;
use Laravel\Scout\Searchable;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;

#[Fillable([
    'company_id', 'category_id', 'name', 'slug', 'description',
    'image_url', 'base_price', 'cost_price', 'sku', 'barcode',
    'is_serialized', 'warranty_period', 'is_active',
])]
class Product extends Model implements Explored
{
    use Searchable, LogsActivity;

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()->logFillable()->logOnlyDirty()->dontSubmitEmptyLogs();
    }

    protected static function booted(): void
    {
        $flush = function (Product $product) {
            \Illuminate\Support\Facades\Cache::tags(["products:{$product->company_id}"])->flush();
        };

        static::saved($flush);
        static::deleted($flush);
    }

    protected function casts(): array
    {
        return [
            'base_price' => 'decimal:2',
            'cost_price' => 'decimal:2',
            'is_serialized' => 'boolean',
            'is_active' => 'boolean',
        ];
    }

    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    public function variants(): HasMany
    {
        return $this->hasMany(ProductVariant::class);
    }

    public function modifierGroups(): BelongsToMany
    {
        return $this->belongsToMany(ModifierGroup::class);
    }

    public function serialNumbers(): HasMany
    {
        return $this->hasMany(SerialNumber::class);
    }

    /**
     * `image_url` stores a disk-relative path (Filament's FileUpload manages
     * it that way) - resolve it to a real URL for display.
     */
    public function imageUrl(): ?string
    {
        return $this->image_url ? Storage::disk('minio')->url($this->image_url) : null;
    }

    /**
     * The smaller companion image generated by ImageOptimizer::store() -
     * use this in product grids (POS/eMenu) instead of the full-size image.
     */
    public function imageThumbUrl(): ?string
    {
        return \App\Support\ImageOptimizer::thumbUrl('minio', $this->image_url);
    }

    public function mappableAs(): array
    {
        return [
            'id' => 'keyword',
            'company_id' => 'keyword',
            'category_id' => 'keyword',
            'name' => 'text',
            'description' => 'text',
            'category_name' => 'text',
            'sku' => 'keyword',
            'barcode' => 'keyword',
            'variant_names' => 'text',
            'variant_skus' => 'keyword',
            'variant_barcodes' => 'keyword',
            'base_price' => 'float',
            'is_active' => 'boolean',
        ];
    }

    public function toSearchableArray(): array
    {
        $this->loadMissing(['category', 'variants']);

        return [
            'id' => (string) $this->id,
            'company_id' => (string) $this->company_id,
            'category_id' => (string) $this->category_id,
            'name' => $this->name,
            'description' => $this->description,
            'category_name' => $this->category?->name,
            'sku' => $this->sku,
            'barcode' => $this->barcode,
            'variant_names' => $this->variants->pluck('name')->filter()->values()->all(),
            'variant_skus' => $this->variants->pluck('sku')->filter()->values()->all(),
            'variant_barcodes' => $this->variants->pluck('barcode')->filter()->values()->all(),
            'base_price' => (float) $this->base_price,
            'is_active' => (bool) $this->is_active,
        ];
    }

    public function shouldBeSearchable(): bool
    {
        return (bool) $this->is_active;
    }
}
